language: node_js
node_js:
- 10.15.2
before_script:
- npm run build
deploy:
  provider: npm
  email: hideki@shiro.be
  api_key:
    secure: b7672QRwmjSAu/bcPt5Z7ykjp+Rm8cV7+wZDDDhI/yZRqcgNHmvoyIFUYPYJBxJMam/ZM7clbm/MDqDKSB0FuGGw+eAsZXMiitkMu40ewwxMML3w8y+ZiMnp0rYwvvIGUf/Xt1hp0Myzrv5Mm0/WFYkTQ76fOPk85KZBHxtCj7I=
  on:
    tags: true
    all_branches: true
